#server:
#  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/security_food_service
#    password:
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id:
#            client-secret:
#            scope:
#              - user:email
#              - read:user